language: python
sudo: false
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"

install:
 - "pip install -r requirements.txt"
 - "pip install ."

script:
  - "py.test --cov pyspark_xgboost --cov-report term-missing tests/"

notifications:
  email:
    on_success: change
    on_failure: always
